#!/usr/bin/env bash
# Installing Nginx on Server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
nl="\\\tadd_header X-Served-By \$hostname;"
sed -i -e "/sendfile/i $nl" /etc/nginx/nginx.conf
sudo service nginx restart
