#!/usr/bin/env bash
# Installing Nginx on Server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo sed -i "46i\\\tadd_header X-Served-By $HOSTNAME;"
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
