#!/usr/bin/env bash
# Display Holberton school 10 times using a while and if else statement

x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    elif [ $x -eq 8 ]
    then
        echo "good luck"
    else
    fi
    x=$((x+1))
done