#!/usr/bin/env bash
# Name of the created private key must be holberton
# Number of bits in the created key to be created 4096
# The created key must be protected by a passphrase betty

ssh-keygen -t rsa -b 4096 -f holberton -P betty